site_name: RCC User Guide
theme:
   name: 'material'
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - "Account and Allocation Management":
    - Overview: account_allocation_management_overview.md
    - Account Management: create_and_manage_accounts.md
    - Allocation Management: request_and_manage_allocations.md
  - "Midway2 and Midway3":
    - Getting Started: midway3_getting_started.md
    - Hardware Overview: midway3_hardware_overview.md
    - Connecting to Midway: midway3_connecting.md
    - "Data Management":
      - Data Transfer: midway3_data_transfer.md
      - Data Storage: midway3_data_storage.md
    - "Running Jobs":
      - Overview: midway3_jobs_overview.md
      - Job Management: midway3_job_management.md
      - Interactive Jobs: midway3_interactive_jobs.md
      - Batch Jobs: midway3_batch_jobs.md
      - Example Job Submission Scripts: example_job_scripts.md
    - "Software":
      - Overview: midway3_software_overview.md
      - "Commonly Used Applications":
        - Python and Conda: midway3_python.md
        - Jupyter: midway3_jupyter.md
        - Tensorflow and PyTorch: midway3_tf_pytorch.md
      - List of All Software: midway3_software_list.md
      - Request New Software: midway3_software_requests.md
    - Troubleshooting and FAQ: midway3_troubleshooting.md
  - "MidwayR":
      - midwayR_getting_started.md
  - "Other Systems":
    - "Beagle3":
      - beagle3_hardware.md
    - "DaLI":
      - dali_hardware.md
    - "MidwaySSD":
      - midwayssd_hardware.md
    - "Skyway":
      - skyway_hardware.md
  - "Facility Policies":
    - facility_policies.md
  - "Tutorials":
    - tutorial_01.md
  - "Help":
    - Frequently Asked Questions: general_faq.md
    - Contact Us: contact_us.md

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - wikilinks