site_name: RCC User Guide
repo_url: https://rcc.uchicago.edu/
repo_name: Main RCC website
theme:
  name: 'material'
  # name: 'readthedocs'
  features:
    - content.code.copy
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - Home: 'index.md' 
  - Accessing RCC resources: connecting.md 
  - 'SSH': 
    - Basics: ssh.md 
    - Advanced: ssh-advance.md 
  - 'ThinLinc': 
    - Basics: thinlinc.md
    - Troubleshooting: thinlinc-advance.md
  - SAMBA: samba.md
  - Globus: 
    - Access Files: globus.md
    - Transfer Files: globus-transfer-files.md
  - HTTP: http.md
  - Storage: storage.md 
  - SLURM: 
    - Basics: slurm.md
    - SBATCH: slurm-sbatch.md 
    - SINTERACTIVE: slurm-sinteractive.md
  - Software & Compiling:
    - Overview: software/index.md
    - Commonly Used Applications:
      - Alphafold: software/apps-and-envs/alphafold.md  
      - CryoSPARC: software/apps-and-envs/cryosparc.md         
      - GROMACS: software/apps-and-envs/gromacs.md
      - LAMMPS: software/apps-and-envs/lammps.md
      - MATLAB: software/apps-and-envs/matlab.md
      - NAMD: software/apps-and-envs/namd.md
      - Mathematica: software/apps-and-envs/mathematica.md
      - OpenMM: software/apps-and-envs/openmm.md
      - Perl: software/apps-and-envs/perl.md
      - Python, Anaconda, Jupyter Notebook & JupyterLab: software/apps-and-envs/python.md
      - R and RStudio: software/apps-and-envs/r.md
      - Singularity: software/apps-and-envs/singularity.md
      - Spark: software/apps-and-envs/spark.md
      - Stata: software/apps-and-envs/stata.md
      - Tensorflow and PyTorch: software/apps-and-envs/tf-and-torch.md
    - Compiling:
      - Compilers: software/compilers.md
      - Libraries: software/libraries.md
      - CMake: software/cmake.md
      - Developer Tools: software/dev-tools.md
  - Partitions: partitions.md
  - Databases: 
    - BFI: databases-bfi.md 
  - "MidwayR3":
    - Overview: midwayR3/overview.md
    - Accessing: midwayR3/accessing.md
    - Connecting: midwayR3/connecting.md
    - Data transfer: midwayR3/data-transfer.md
    - Running jobs: midwayR3/running-jobs.md
    - Partitions: midwayR3/partitions.md
  - "DaLI": https://dali.uchicago.edu/
  - "GM4": https://gm4.rcc.uchicago.edu/
  - "Beagle3": https://beag3.rcc.uchicago.edu/
  - "MidwaySSD": https://midwayssd.rcc.uchicago.edu/
  - "Skyway": https://cloud-skyway.rcc.uchicago.edu/
  - GIS: 
    - Overview: gis/index.md
    - Geocoding: gis/geocoding.md 
  - "User Policy": user-policy.md
  - "Glossary": glossary.md
  - "Tutorials":
    - KICP Tutorial: tutorials/kicp.md
    - MSCA Tutorial: tutorials/msca.md
  - "Mistakes to avoid": mistakes-to-avoid/list.md
  - "FAQ": 
    - Allocations: FAQ/accounts-and-allocations.md
    - Connecting to Midway: FAQ/connecting.md
    - Data Management: FAQ/data-management.md
    - Software: FAQ/software.md
    - Running Jobs: FAQ/running-jobs.md
    - General Questions: FAQ/general.md

extra:
  analytics:
    provider: google
    property: G-BE96ZBJB57

# extra:
#  consent:
#    title: Cookie consent
#    description: > # (1)
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better. 

extra_javascript:
  - stylesheets/gtag.js

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - wikilinks
  - tables
  - attr_list
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.critic

plugins:
  - monorepo
  - search:
      separator: '[\s\.]+'
