site_name: RCC User Guide
theme:
   name: 'material'
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - "Accounts and Allocations": https://rcc.uchicago.edu/accounts-allocations
  - "Midway2 and Midway3":
   # - Connecting: midway23/midway_connecting.md
    - Getting Started: midway23/midway_getting_started.md
    - Hardware Overview:  midway23/midway_hardware_overview.md
    - Connecting to Midway: midway23/midway_connecting.md
    - "Data Management":
      - Data Transfer: midway23/midway_data_transfer.md
      - Data Storage: midway23/midway_data_storage.md
      - File System Permissions: midway23/midway_file_permissions.md
    - "Running Jobs":
      - Overview: midway23/midway_jobs_overview.md
      - Submitting Jobs: midway23/midway_submitting_jobs.md
      - Managing Jobs: midway23/midway_job_management.md
      - Example Job Submission Scripts: midway23/examples/example_job_scripts.md
    - "Software":
      - Overview: midway23/software/midway_software_overview.md
      - "Commonly Used Applications":
        - Python and Conda: midway23/midway3_python.md
        - Jupyter: midway23/midway3_jupyter.md
        - Tensorflow and PyTorch: midway23/midway3_tf_pytorch.md
      - List of All Software: midway23/midway3_software_list.md
      - Request New Software: midway23/midway3_software_requests.md
    - Troubleshooting and FAQ: midway23/midway_troubleshooting.md
  
  - "Specialized Systems and Partitions":
    - "MidwayR":
      - Overview: midwayr/midwayr_overview.md
    - "Beagle3":
      - Overview: beagle3/beagle3_overview.md
    - "DaLI":
      - Overview: dali/dali_overview.md
    - "MidwaySSD":
      - Overview: midwayssd/midwayssd_overview.md
    - "Skyway":
      - Overview: skyway/skyway_overview.md
  - "RCC User Policy": user_policy.md
  - "Tutorials":
    - tutorial_01.md
  - "Help":
    - Glossary: glossary.md
    - Frequently Asked Questions: general_faq.md
    - Contact Us: contact_us.md

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - wikilinks
  - tables
  - attr_list
  - md_in_html
