site_name: RCC User Guide
theme:
   name: 'material'
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - "Account and Allocation Management":
    - Overview: account_allocation_management_overview.md
    - Account Management: create_and_manage_accounts.md
    - Allocation Management: request_and_manage_allocations.md
  - "Midway2 and Midway3":
   # - Connecting: midway23/midway_connecting.md
    - Getting Started: midway23/midway_getting_started.md
    - Hardware Overview:  midway23/midway_hardware_overview.md
    - Connecting to Midway: midway23/midway_connecting.md
    - "Data Management":
      - Data Transfer: midway23/midway3_data_transfer.md
      - Data Storage: midway23/midway3_data_storage.md
      - File System Permissions: midway23/midway3_file_permissions.md
    - "Running Jobs":
      - Overview: midway23/midway_jobs_overview.md
      - Submitting Jobs: midway23/midway_submitting_jobs.md
      - Managing Jobs: midway23/midway_job_management.md
      - Example Job Submission Scripts: midway23/examples/example_job_scripts.md
      # - Array:  midway23/examples/array.md
      # - Bigmem:  midway23/examples/bigmem.md
      # - Cron:  midway23/examples/cron.md
      # - Dependency:  midway23/examples/dependency.md
      # - GPU:  midway23/examples/gpu.md
      # - Hybrid:  midway23/examples/hybrid.md
      # - MPI:  midway23/examples/mpi.md
      # - Srun parallel:  midway23/examples/srun.md
    - "Software":
      - Overview: midway3_software_overview.md
      - "Commonly Used Applications":
        - Python and Conda: midway3_python.md
        - Jupyter: midway3_jupyter.md
        - Tensorflow and PyTorch: midway3_tf_pytorch.md
      - List of All Software: midway3_software_list.md
      - Request New Software: midway3_software_requests.md
    - Troubleshooting and FAQ: midway3_troubleshooting.md
  - "MidwayR":
      - Overview: midwayr/midwayR_overview.md
  - "Other Systems":
    - "Beagle3":
      - Overview: other_systems/beagle3_overview.md
    - "DaLI":
      - Overview: other_systems/dali_overview.md
    - "MidwaySSD":
      - Overview: other_systems/midwayssd_overview.md
    - "Skyway":
      - Overview: other_systems/skyway_overview.md
  - "Facility Policies":
    - facility_policies.md
  - "Tutorials":
    - tutorial_01.md
  - "Help":
    - Glossary: glossary.md
    - Frequently Asked Questions: general_faq.md
    - Contact Us: contact_us.md

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - wikilinks
  - tables
