site_name: RCC User Guide
theme:
   name: 'material'
   features:
    - content.code.copy
    - navigation.sections
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - "Midway2 and Midway3":
   # - Connecting: midway23/midway_connecting.md
    - Getting Started: midway23/midway_getting_started.md
    - Hardware Overview:  midway23/midway_hardware_overview.md
    - Connecting to Midway: midway23/midway_connecting.md
    - "Data Management":
      - Data Transfer: midway23/midway_data_transfer.md
      - Data Storage: midway23/midway_data_storage.md
      - File System Permissions: midway23/midway_file_permissions.md
    - "Running Jobs":
      - Overview: midway23/midway_jobs_overview.md
      - Submitting Jobs: midway23/midway_submitting_jobs.md
      - Managing Jobs: midway23/midway_job_management.md
      - Example Batch Job Scripts: midway23/examples/example_job_scripts.md
    - Partitions: midway23/midway_partitions.md
    - "Software":
      - Overview: midway23/software/midway_software_overview.md
      - "Commonly Used Applications":
        - Python, Anaconda, & Jupyter Notebook: midway23/software/apps_and_envs/python.md
        - R: midway23/software/apps_and_envs/r.md
        - MATLAB: midway23/software/apps_and_envs/matlab.md
        - Stata: midway23/software/apps_and_envs/stata.md
        - Mathematica: midway23/software/apps_and_envs/mathematica.md
        - Perl: midway23/software/apps_and_envs/perl.md
        - Spark: midway23/software/apps_and_envs/spark.md
        - Tensorflow and PyTorch: midway23/software/apps_and_envs/tf_and_torch.md
        - GROMACS: midway23/software/apps_and_envs/gromacs.md
        - LAMMPS: midway23/software/apps_and_envs/lammps.md
        - NAMD: midway23/software/apps_and_envs/namd.md
      - Compiling:
        - Compilers: midway23/software/compilers.md
        - Libraries: midway23/software/libraries.md
        - CMake: midway23/software/cmake.md
  
  - "Specialized Systems and Partitions":
    - "MidwayR": https://sde-midwayr.rcc.uchicago.edu/user-guide/
    - "Beagle3": beagle3/beagle3_overview.md
    - "DaLI": https://dali.uchicago.edu/using-dali/
    - "MidwaySSD": https://midwayssd.rcc.uchicago.edu/using-midwayssd/
    - "Skyway": skyway/skyway_overview.md
  - "RCC User Policy": user_policy.md
  - "Glossary": glossary.md
  - "Frequently Asked Questions": 
    - Accounts and Allocations: FAQ/accounts_and_allocations_faq.md
    - Connecting to Midway: FAQ/connecting_faq.md
    - Data Management: FAQ/data_management_faq.md
    - Software: FAQ/software_faq.md
    - Running Jobs: FAQ/running_jobs_faq.md
    - General Questions: FAQ/general_faq.md

extra:
  analytics:
    provider: google
    property: G-BE96ZBJB57

extra:
  consent:
    title: Cookie consent
    description: > # (1)
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_javacript: [gtag.js]

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - wikilinks
  - tables
  - attr_list
  - md_in_html
  - pymdownx.magiclink
