site_name: 'MidwayR3'
#MidwayR User Guide
nav:
#    - Introduction: index.md
    - System overview: system/index.md
#    - Getting started: getting-started/index.md
    - Accessing: accessing/index.md
    - Connecting: connecting/index.md
    - Storage and data transfer: data-transfer/index.md
    - Running jobs: running-jobs/index.md
    - Partitions: partitions/index.md
    

markdown_extensions:
  - attr_list
  - toc:
      permalink: True
